"""Shared domain identifiers and migration keys."""

CURRENCY_ASSET_TYPE = "CURRENCY"
TICKET_ASSET_TYPE = "TICKET"
PASS_ASSET_TYPE = "PASS"
POINTS_ASSET_TYPE = "POINTS"

PAID_CURRENCY_ASSET_ID = 10001
FREE_CURRENCY_ASSET_ID = 10002
MONTHLY_PASS_ASSET_ID = 10001
POINTS_ASSET_ID = 20001

MONEY_MIGRATION_KEY = "money_integer_cents_v1"
IDENTITY_CONSTRAINTS_MIGRATION_KEY = "identity_session_constraints_v1"
ASSET_REDEEM_CONSTRAINTS_MIGRATION_KEY = "asset_redeem_constraints_v1"
